# Basic Information
title: Mitsuru Mukaigawara
position: PhD Candidate in Government<br>AM Candidate in Statistics
affiliation: Harvard University
affiliation_link:
affiliation_logo:
#email: mitsuru_mukaigawara@g.harvard.edu

# Search Engine Optimization (SEO)
keywords: mitsuru mukaigawara, mukaigawara mitsuru, mitsurumukaigawara, mukaigawaramitsuru, mmukaigawara
description: Mitsuru Mukaigawara is a PhD candidate in Government at Harvard University.
canonical: https://www.mitsurumukaigawara.com/

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# Links
google_scholar: https://scholar.google.com/citations?user=J3swALMAAAAJ&hl=en
cv_link: assets/files/CV.pdf
github_link: https://github.com/mmukaigawara
twitter: https://twitter.com/mitsurumu

# Images (e.g., your profile picture and your website's favicon)
#avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
enable_footnote: false

# Auto Dark Mode
auto_dark_mode: false

# Font
font: "Sans Serif" # or "Sans Serif"

# Google Analytics ID
google_analytics: "G-H25T8JXNQB"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
